### PR TITLE
fix build with gcc 4.8

### PR DESCRIPTION
**Pull request by ffontaine**
Fx the following build failures with gcc 4.8 raised since version 0.9.4 and https://github.com/uoaerg/wavemon/commit/674efd8297997d63481705ece71b83cb19eb3d15 and https://github.com/uoaerg/wavemon/commit/220163d9c8763471edfb528459c788aee07df81d:

```
wavemon.h: In function 'argv_find':
wavemon.h:311:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (size_t i = 0; argv[i]; i++)
  ^

about_scr.c: In function 'scr_about_init':
about_scr.c:40:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (size_t i = 0; i < ARRAY_SIZE(about_lines); i++) {
  ^
about_scr.c:42:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (size_t j = 0; j < strlen(about_lines[i]); j++)
   ^
```

Fixes:
 - http://autobuild.buildroot.org/results/a6ee162cf04b70b144b54e1ca4b7b2421071c50c

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by grrtrr** [comment]
@ffontaine - does the code compile with gcc 4.8 using `-std=c99` in `CFLAGS`?

**Comment by ffontaine** [comment]
Indeed, an other option is to add `-std=gnu99` in `CFLAGS` by updating the following line:
https://github.com/uoaerg/wavemon/blob/9ba71c0caf0286fdc83fe4e798f725e1f0da419b/Makefile.in#L12

It should be noted that adding `-std=c99` will result in a build failure because `sigaction` will be undefined.

I can update the PR if you prefer this solution.

**Comment by grrtrr** [comment]
I am not able to test now, but according to [this comment](https://www.illumos.org/issues/6283) `-std=gnu99` works with a gnu compiler for the `sigaction` struct. There should be a better solution, using appropriate defines instead.

**Comment by grrtrr** [comment]
Can you try the latest update on `master` (https://github.com/uoaerg/wavemon/commit/979a75e13a570b8d9a6b36f8230cc7f50f076aa2)? 

Since the change is in `configure.ac / configure`, you would need to run
```bash
./configure && make 
```

**Comment by ffontaine** [comment]
The build failure is fixed with your patch, I'm closing this PR
