### ISSUE TITLE
Slackware Missing Include NCurses Folder?

### ISSUE THREAD

**Issue by rogerxxxx** [uoaerg/wavemon#95]
I'm getting a lot of undeclared "WACS_*" function errors while trying to build/make the git sources.

Looks like the "WACS_*" functions are defined or the ncurses include files are located within /usr/include/ncurses on slackware-14.2 distribution folder hierarchy.

I tried ./configure --includedir="/usr/include/ncurses" without success.

I do not think I've tried building wavemon on slackware yet.

Oddly, trying to use -ltinfow (or -lncursesw) during configure, gcc fails to build the test program due to the inclusion of -ltinfow within the command gcc incanatation.  So I omitted specifying the libs, then encountered the WACS_* function errors.

**Comment by grrtrr** [comment]
Try slackbuilds - apparently it is up to date up to 0.9.0 - https://slackbuilds.org/repository/14.2/network/wavemon/?search=wavemon

If that works out, could you update the slack build if necessary?

**Comment by rogerxxxx** [comment]
I've been using Gentoo for 10-20 years, and am experimenting with Slackware, the wonderful Unix philosophy adhering distro, on my older laptop.  I don't really want to mess with non-native software repositories, as I want this laptop to remain stable.

(I'm so @#$@# sick of Gentoo developers always breaking things, regardless of what they falsely preach.  They're likely barely avoiding SystemD/Rust inclusion/dependencies, while I still see trickles of SystemD/Rust taking over the system regardless of a users USEFLAGS/wishes.  Starting to wonder if I should jump ship, as I doubt they have corks big enough for their holes!)

As far as packaging, again, not a long time slack user as of yet, however I long ago routinely packaged/compiled packages for distros 15-20 years ago, then a mess of wanna be developers (likely M$ ex-employees) started all grabbing for their favorite linux distribution domain name based email addresses, attaining the more apparent officlal role of developer, and subsequently playing God.  Hence, they tried to turn my volunteer time turned into slave work.

I can more easily grab wavemon via git and compile myself.  Really love that wavemon is very small and lightweight, can easily compile and execute within my home folder.

I'll try to find the build script for their wavemon in the meantime, and research the slackbuilds.org project.  Really liking the fact that a distro is apparently, finally, practicing what they preach.

**Comment by rogerxxxx** [comment]
I've pulled the build script from slackware 14.2 slackbuild.org:
https://slackbuilds.org/repository/14.2/network/wavemon/?search=wavemon

The (wavemon.SlackBuild) build script doesn't do much except dance around with chown, find, xargs, CFLAGS andi install locations, etc...  I saw nothing passing custom include/lib configure options, except SLKCFLAGS/LIBDIRSUFFIX for either blank "" for 32 bit, or "64" for 64 bit libs.  Since this is a 32 bit platform, nothing is really done within the script except determine i586/i686 for march/mtune CFLAGS and also specifying install locations.

Seems something changed from the wavemon-0.9.0 tarball and git, preventing from building on slackware-14.2. 

The /usr/include/ncurses and /usr/include/ncursesw folder/symlinks on both of my platforms look sane.

I also manually included the <ncursesw/curses.h> (etc) to the lhist_scr.c file with no resolve.  Weird!

I removed the "@" from the CC line within the Makefile, and I can visibly see -I/usr/include/ncurses/ within the CC recipe.  (eg. make -n)

Still wavemon-0.9.0 compiles while git fails, likely not finding the /usr/include/ncurses/ header files for some odd reason when encountering lhist_scr.c file.

**Comment by rogerxxxx** [comment]
As to why wavemon-0.9.0 tarball is building on wave slackware 14.2, git lhist_scr.c has WACS_* definitions, while wavemon-0.9.0/lhist_scr.c file contains to WAVS_* definitions.  Hence, no problems with having to find WACS_* definitions.

I also removed the ifdef for ncursesw within the wavemon.h, defaulting to the wavemon-0.9.0/wavemon.h ncurses.h header inclusion statement, still didn't build or find WACS_* definitions.

The WACS_* definitions on slackware-14.2 are defined within /usr/include/curses.h and /usr/include/ncursesw/ncurses.h, with one being a symlink to the other file.

Shrugs... nothing seems to make sense here.

**Comment by grrtrr** [comment]
What is failing? To configure ncurses, one of `ncursesw{5,6}-config` or `ncurses5-config` is used, else it falls back to generic paths.
You can see what it chose in the `CFLAGS` and `LDLIBS` values of the `Makefile`.

**Comment by rogerxxxx** [comment]
Slackware 14.2 (up-to-date)
ncurses-5.9-i486-4

# ls -al /usr/include/ncursesw                                                                                              
lrwxrwxrwx 1 root root 7 2021-02-16 17:23 /usr/include/ncursesw -> ncurses/

# ls -al /usr/include/ncurses/curses.h                                                                                     
-rw-r--r-- 1 root root 95K 2015-05-01 15:22 /usr/include/ncurses/curses.h

# ls -al /usr/include/ncurses/ncurses.h                                                                                    
lrwxrwxrwx 1 root root 8 2021-02-16 17:23 /usr/include/ncurses/ncurses.h -> curses.h

# cat /usr/include/ncurses/curses.h |grep WACS_S9                                                                          
#define WACS_S9         NCURSES_WACS('s') /* scan line 9 */

Git pull as of today, 2021.02.19
See attached config.log

$ make
echo ' CC  ' lhist_scr.c
 CC   lhist_scr.c
cc -Og -Wall -g -ggdb -I/usr/include/ncurses/ -pthread -I/usr/include/libnl3   -DPACKAGE_NAME=\"wavemon\" -DPACKAGE_TARNAME=\"wavemon-current\" -DPACKAGE_VERSION=\"0.9.3\" -DPACKAGE_STRING=\"wavemon\ 0.9.3\" -DPACKAGE_BUGREPORT=\"https://github.com/uoaerg/wavemon\" -DPACKAGE_URL=\"https://github.com/uoaerg/wavemon\" -DSTDC_HEADERS=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_NCURSES_H=1 -DHAVE_FCNTL_H=1 -DHAVE_NETDB_H=1 -DHAVE_SYS_IOCTL_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_NET_IF_ARP_H=1 -DHAVE_NETINET_ETHER_H=1 -DHAVE_NET_ETHERNET_H=1 -DHAVE_PTHREAD_H=1 -DHAVE_NCURSESW_CURSES_H=1 -DHAVE_SYS_SOCKET_H=1 -DHAVE_LINUX_IF_H=1 -DHAVE_LINUX_WIRELESS_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_LIBM=1 -DHAVE_LIBNCURSESW=1 -DHAVE_LIBCAP=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_ETHER_NTOHOST=1 -c -o lhist_scr.o lhist_scr.c
lhist_scr.c: In function 'hist_plot':
lhist_scr.c:214:3: error: unknown type name 'cchar_t'
   cchar_t * wch;
   ^
lhist_scr.c:217:10: error: 'WACS_S9' undeclared (first use in this function)
    wch = WACS_S9;
          ^
lhist_scr.c:217:10: note: each undeclared identifier is reported only once for each function it appears in
lhist_scr.c:219:10: error: 'WACS_S7' undeclared (first use in this function)
    wch = WACS_S7;
          ^
lhist_scr.c:221:10: error: 'WACS_HLINE' undeclared (first use in this function)
    wch = WACS_HLINE;
          ^
lhist_scr.c:223:10: error: 'WACS_S3' undeclared (first use in this function)
    wch = WACS_S3;
          ^
lhist_scr.c:225:10: error: 'WACS_S1' undeclared (first use in this function)
    wch = WACS_S1;
          ^
lhist_scr.c:228:3: warning: implicit declaration of function 'mvwadd_wch' [-Wimplicit-function-declaration]
   mvwadd_wch(w_lhist, hist_y(level), hist_x(xval), wch);
   ^
Makefile:28: recipe for target 'lhist_scr.o' failed
make: *** [lhist_scr.o] Error 1

2 :-(

Attached config.log

**Comment by grrtrr** [comment]
Apologies - that is a bug I introduced in 4b775eb when testing a fix for #97. I will add the missing `#include` shortly, that should fix it.

**Comment by rogerxxxx** [comment]
I try to merrily hint on the issue before dumping a lot of logs.

I cannot believe I was not able to hack in the missing include!

**Comment by grrtrr** [comment]
It actually is an old bug (since dd9a5e08e239fe0e10f4dacaa651c31262e30f5b), on my system it compiles even with ncurses-6.
Does your slackware build compile now?

**Comment by rogerxxxx** [comment]
Just did a git pull now, 20210220 21:00 EST, compile is still bailing on the same errors.

I see the updates to several affected *.h/*.c files.

Like I said, I don't get it.  The include files are there, but the cc statement keeps bailing suggesting missing includes.  Even I should be able to manually hack-in the include file, and the compiler should then find the includes/functions.  Not happening though for some odd reason.

**Comment by grrtrr** [comment]
The output of `ncursesw5-config --cflags` with the slackware curses5 package is empty.

Can you add the following definition to the `DEFS` inside the generated `Makefile`?
```Makefile
DEFS ?= -D_XOPEN_SOURCE_EXTENDED=1  # ...
```
If that works, I will add it to the header files.

**Comment by rogerxxxx** [comment]
I had my doubts as I do not see anything to deal with ncurses and my config.log seems to indicate finding all types of ncurses successfully, but tried anyways.  The ncurses related include errors still occurred.

My current config.log shows:
checking for addnwstr in -lncursesw
gcc -o conftest -Og -Wall -g -ggdb -I/usr/include/ncurses/ -pthread -lncursesw conftest.c -lncursesw -lm >&5
$?=0
result: yes

Not sure if the attached config.log shows your specified error.

**Comment by rogerxxxx** [comment]
Think your typewriter/keyboard was typing faster than you were thinking... 

The keyboard should have typed, look for the line within the Makefile beginning with  "DEFS ?= ", and add "-D_XOPEN_SOURCE_EXTENDED=1" at the end of the line.

Success, everything finishes with echo $? = 0!

**Comment by grrtrr** [comment]
Great, I will add a commit for this.
